var rankings = TAFFY([
    {"id": 1, "ranking": "Most populous countries", "value_name": "Population"},
    {"id": 2, "ranking": "Less populous countries", "value_name": "Population"},
    {"id": 3, "ranking": "Larger countries", "value_name": "Area (km2)"},
    {"id": 4, "ranking": "Smaller countries", "value_name": "Area (km2)"},
    {"id": 5, "ranking": "Most populated countries", "value_name": "Density (/km2)"},
    {"id": 6, "ranking": "Less populated countries", "value_name": "Density (/km2)"}
]);
var inside_rankings = TAFFY([
    {"ranking_id": 1, "position": 1, "nome": "China", "value": "1,369,880,000"},
    {"ranking_id": 1, "position": 2, "nome": "India", "value": "1,271,310,000"},
    {"ranking_id": 1, "position": 3, "nome": "United States", "value": "321,013,000"},
    {"ranking_id": 1, "position": 4, "nome": "Indonesia", "value": "255,461,700"},
    {"ranking_id": 1, "position": 5, "nome": "Brazil", "value": "204,321,000"},
    {"ranking_id": 2, "position": 1, "nome": "Vatican City", "value": "839"},
    {"ranking_id": 2, "position": 2, "nome": "Nauru", "value": "10,084"},
    {"ranking_id": 2, "position": 3, "nome": "Tuvalu", "value": "11,323"},
    {"ranking_id": 2, "position": 4, "nome": "Palau", "value": "20,901"},
    {"ranking_id": 2, "position": 5, "nome": "San Marino", "value": "32,789"},
    {"ranking_id": 3, "position": 1, "nome": "Russia", "value": "17,098,242"},
    {"ranking_id": 3, "position": 2, "nome": "Canada", "value": "9,984,670"},
    {"ranking_id": 3, "position": 3, "nome": "China", "value": "9,572,900"},
    {"ranking_id": 3, "position": 4, "nome": "United States", "value": "9,526,468"},
    {"ranking_id": 3, "position": 5, "nome": "Brazil", "value": "8,515,767"},
    {"ranking_id": 4, "position": 1, "nome": "Vatican City", "value": "0.44"},
    {"ranking_id": 4, "position": 2, "nome": "Monaco", "value": "2.02"},
    {"ranking_id": 4, "position": 3, "nome": "Nauru", "value": "21"},
    {"ranking_id": 4, "position": 4, "nome": "Tuvalu", "value": "26"},
    {"ranking_id": 4, "position": 5, "nome": "San Marino", "value": "61"},
    {"ranking_id": 5, "position": 1, "nome": "Monaco", "value": "16,923"},
    {"ranking_id": 5, "position": 2, "nome": "Singapore", "value": "7,148"},
    {"ranking_id": 5, "position": 3, "nome": "Vatican City", "value": "1,877"},
    {"ranking_id": 5, "position": 4, "nome": "Bahrain", "value": "1,646"},
    {"ranking_id": 5, "position": 5, "nome": "Malta", "value": "1,322"},
    {"ranking_id": 6, "position": 1, "nome": "Mongolia", "value": "1.7"},
    {"ranking_id": 6, "position": 2, "nome": "Namibia", "value": "2.6"},
    {"ranking_id": 6, "position": 3, "nome": "Iceland", "value": "3.1"},
    {"ranking_id": 6, "position": 4, "nome": "Mauritania", "value": "3.2"},
    {"ranking_id": 6, "position": 5, "nome": "Suriname", "value": "3.2"}
]);